name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:

  static_analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run Rustfmt
      run: cargo fmt -- --check

    - name: Run Clippy
      run: cargo clippy --workspace --all-targets -- -D warnings

  mdtomlfmt:
    name: Generic format (md,toml)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run dprint
      run: |
        curl -fsSL https://dprint.dev/install.sh | sh
        /home/runner/.dprint/bin/dprint check

  build:
    name: Build
    strategy:
      matrix:
        rust: [
          1.51.0,
          stable,
          nightly
        ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Rust ${{ matrix.rust }}
      uses: actions-rs/toolchain@v1.0.7
      with:
        toolchain: ${{ matrix.rust }}
        override: true
        profile: minimal

    - uses: Swatinem/rust-cache@v1.3.0

    - name: Build
      run: cargo build --verbose

    - name: Build with feature 'serde_support'
      run: cargo build --verbose --features serde_support

    - name: Build wasm with all features
      run: cargo build --verbose --all-features

  test:
    name: Test
    strategy:
      matrix:
        rust: [
          stable,
          nightly
        ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Rust ${{ matrix.rust }}
      uses: actions-rs/toolchain@v1.0.7
      with:
        toolchain: ${{ matrix.rust }}
        override: true
        profile: minimal

    - uses: Swatinem/rust-cache@v1.3.0

    - run: cargo test --verbose --all-features
