name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: dtolnay/rust-toolchain@master
      with:
        components: clippy,rustfmt
        toolchain: stable

    - run: cargo fmt --all --check

    - run: cargo clippy --workspace --all-targets --all-features -- -D warnings

  mdtomlfmt:
    name: Generic format (md,toml)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run dprint
      run: |
        curl -fsSL https://dprint.dev/install.sh | sh
        /home/runner/.dprint/bin/dprint check

  build_msrv:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: 1.63

    - uses: Swatinem/rust-cache@v2.7.3

    - run: cargo build --workspace --all-features

  build_features:
    name: Build with varying features
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable

    - run: cargo install cargo-hack

    - uses: Swatinem/rust-cache@v2.7.3

    - run: cargo hack build --workspace --each-feature

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable

    - uses: Swatinem/rust-cache@v2.7.3

    - run: cargo test --workspace --all-features
