name: Create release

on:
  pull_request:
    types:
      - closed

jobs:
  create_release:
    name: Create from merged release branch
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/')
    uses: monero-rs/workflows/.github/workflows/create-release.yml@v2.0.2

  release_to_crates:
    name: Publish the new release to crates.io
    uses: monero-rs/workflows/.github/workflows/release-to-crates-io.yml@v2.0.2
    # Do not run before creating the release is done
    needs: create_release
    secrets:
      cratesio_token: ${{ secrets.H4SH3D_CARGO_REGISTRY_TOKEN }}
